export const VK_CLIENT_ID = process.env.VITE_VK_CLIENT_ID
export const VK_CLIENT_SECRET = process.env.VITE_VK_CLIENT_SECRET
export const VK_CLIENT_DEFAULT_REDIRECT =
  process.env.VITE_VK_CLIENT_DEFAULT_REDIRECT

export const TELEGRAM_BOT_TOKEN = process.env.VITE_TELEGRAM_BOT_TOKEN
