export const MAIL_SMTP_SERVER = process.env.VITE_MAIL_SMTP_SERVER
export const MAIL_LOGIN = process.env.VITE_MAIL_LOGIN
export const MAIL_PASSWORD = process.env.VITE_MAIL_PASSWORD
export const MAIL_ORIGIN_DOMAIN = process.env.VITE_MAIL_ORIGIN_DOMAIN
export const MAIL_DNS_CHECK_SELECTOR = process.env.VITE_MAIL_DNS_CHECK_SELECTOR
export const MAIL_PRIVATE_KEY_FILENAME =
  process.env.VITE_MAIL_PRIVATE_KEY_FILENAME
